"""fav posts

Revision ID: 52092cb33eaa
Revises: ce77996e3c51
Create Date: 2020-04-19 19:46:55.810937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52092cb33eaa'
down_revision = 'ce77996e3c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
