"""init palettes

Revision ID: 62a54a871d8d
Revises: 
Create Date: 2020-04-04 14:19:12.603545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a54a871d8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palette',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_palette_colors'), 'palette', ['colors'], unique=False)
    op.create_index(op.f('ix_palette_slug'), 'palette', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_palette_slug'), table_name='palette')
    op.drop_index(op.f('ix_palette_colors'), table_name='palette')
    op.drop_table('palette')
    # ### end Alembic commands ###
