"""unique vk domain

Revision ID: dc3ac32df755
Revises: 84ed8e4ce546
Create Date: 2020-04-09 10:32:52.262096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3ac32df755'
down_revision = '84ed8e4ce546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user', ['vk_domain'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user', type_='unique')

    # ### end Alembic commands ###
