"""init posts table

Revision ID: f98bb54185d7
Revises:
Create Date: 2020-04-06 15:17:07.043682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98bb54185d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palette',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('colors', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('palette', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_palette_colors'), ['colors'], unique=False)
        batch_op.create_index(batch_op.f('ix_palette_slug'), ['slug'], unique=True)

    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('palette', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['palette'], ['palette.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_vk_id'), ['vk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_vk_id'))

    op.drop_table('post')
    with op.batch_alter_table('palette', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_palette_slug'))
        batch_op.drop_index(batch_op.f('ix_palette_colors'))

    op.drop_table('palette')
    # ### end Alembic commands ###
